version: '3.8'

services:
  web:
    build: .
    container_name: bagaicha-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: always
